### ISSUE TITLE
Could you help to upload the dataset of the contest?

### ISSUE THREAD

**Issue by Jack12xl** [GeneralLi95/deepglobe_land_cover_classification_with_deeplabv3#1]
Hi there! Could u plz help upload the dataset of the DeepGlobe Land Cover Classification Challenge to cloud like 百度云盘. I couldn't access the dataset since the contest haven't accepted me 0.0

**Comment by GeneralLi95** [comment]
Sure. Dataset will be published during New Year's Holiday.

**Comment by GeneralLi95** [comment]
Hi @Jack12xl. You can download the dataset by 'baiduyun' now.

**Comment by Jack12xl** [comment]
👍
